### PR TITLE
Fix name of grouping_hash (was group_hash)

### PR DESCRIPTION
**Pull request by mehcode**

### CODE REVIEW

**Comment by bkchr** [comment]
Is the `PAYLOAD_VERSION` still 4?

**Comment by mehcode** [comment]
Yeah. I don't think it was ever `groupHash`. It just seems to be a simple typo. I just noticed my events weren't getting the grouping hash applied after I switched to upstream from my fork and investigated.

**Comment by bkchr** [comment]
Okay :) Thank you.

**Comment by mehcode** [comment]
Thanks for merging it. 😄 Do you mind putting out a cargo release when you get a chance.

**Comment by bkchr** [comment]
Will do that tomorrow.

**Comment by bkchr** [comment]
@mehcode 0.2.1 is out :)

**Comment by mehcode** [comment]
@bkchr Thank you 😄

**Pull request merged**
