### PR TITLE
Add 'grouping_hash'

### PR DESCRIPTION
**Pull request by mehcode**
I don't really like just adding more parameters to `notify`. Any other ideas?

### CODE REVIEW

**Comment by bkchr** [comment]
We could introduce a builder like structure? So, notify() returns the Builder and then for each parameter, a function exists. What do you think?

**Comment by bkchr** [comment]
Could you look at https://github.com/superscale/bugsnag-rs/pull/4.

For your case the new call would look like:
```api.notify("Panic", "ahh an error").grouping_hash("myhash).severity(Severity::Error);```

**Comment by mehcode** [comment]
Looks awesome. Thanks for putting that together. 👍

**Comment by bkchr** [comment]
@mehcode I released version 0.2.0, that contains the new interface.

**Pull request closed without merging**
